# This file serves as the base to build on top on.
version: "3.8"
services:
  # https://hub.docker.com/_/postgres
  postgres:
    # https://hub.docker.com/_/postgres/tags
    image: postgres:18.1-alpine

    # https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: unless-stopped

    # Default postgres port. This line is not here to configure something. It is more of a reminder so chaning it will do nothing
    ports:
      - 5432

    # https://docs.docker.com/compose/environment-variables/set-environment-variables/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Missing environment variable see readme}
      POSTGRES_USER: paperless
      POSTGRES_DB: paperless

    # https://docs.docker.com/storage/volumes/
    # Define a named volume to persist data
    volumes:
      - paperlessPostgressData:/var/lib/postgresql

  # https://hub.docker.com/_/redis
  redis:
    # https://hub.docker.com/_/redis/tags
    image: redis:8.0-alpine

    # https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: unless-stopped

    # Default redis port. This line is not here to configure something. It is more of a reminder so chaning it will do nothing
    ports:
      - 6379

  # https://hub.docker.com/r/gotenberg/gotenberg
  gotenberg:
    # https://hub.docker.com/r/gotenberg/gotenberg/tags
    image: gotenberg/gotenberg:8.24

     # https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  # https://hub.docker.com/r/apache/tika
  tika:
    # https://hub.docker.com/r/apache/tika/tags
    image: apache/tika:3.2.3.0

    # https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: unless-stopped

  # https://hub.docker.com/r/paperlessngx/paperless-ngx
  paperless:
    # https://hub.docker.com/r/paperlessngx/paperless-ngx/tags
    image: paperlessngx/paperless-ngx:2.20

    # https://www.baeldung.com/ops/docker-compose-restart-policies
    restart: unless-stopped

    # Default paperless port. This line is not here to configure something. It is more of a reminder so chaning it will do nothing
    ports:
      - 8000

    # https://docs.paperless-ngx.com/configuration/
    # All configs should be set here as environment variable
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD?Missing environment variable see readme}
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_CONSUMER_DISABLE: "true"
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

    # https://docs.docker.com/storage/volumes/
    # Define a named volume to persist data
    volumes:
      - paperlessData:/usr/src/paperless/data
      - paperlessMedia:/usr/src/paperless/media

    # https://docs.docker.com/compose/compose-file/05-services/#depends_on
    depends_on:
      - postgres
      - redis

# https://docs.docker.com/storage/volumes/
volumes:
  paperlessData:
  paperlessMedia:
  paperlessPostgressData: